# public/admin/config.yml
backend:
  name: github
  branch: main
  repo: 1226085293/1226085293.github.io

local_backend: true
# CMS 用户界面将在页面顶部的固定区域添加一个链接，方便内容作者轻松返回您的主站点
display_url: https://www.muzzik.cc
# 相对于 repo 基础的上传文件的保存文件夹路径
media_folder: 'public/static/blog'
# 媒体库上传文件的文件夹路径
public_folder: '/static/blog'

collections:
- name: 'posts'
  label: '帖子'
  label_singular: 'Post'
  folder: 'data/blog'
  format: "frontmatter"
  extension: "mdx"
  create: true
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  fields:
    - name: 'title'
      label: '标题'
      widget: 'string'
    - name: 'date'
      label: '时间'
      widget: 'datetime'
      format: 'YYYY-MM-DD HH:mm:ss'
    - name: 'image'
      required: false
      label: '顶部图'
      widget: 'image'
    - name: 'summary'
      label: '简述'
      widget: 'string'
    - name: "tags"
      required: false
      label: "标签"
      widget: "select"
      multiple: true
      options: ["CocosCreator", "Web", "原生", "AI", "Typescript", "Javascript", "Lua", "Nodejs", "C++", "Github", "图形学", "图形处理", "开发工具", "PC", "Cocos2DX", "Unity"]
    - name: 'body'
      label: '内容'
      widget: 'markdown'
