# public/admin/config.yml
backend:
  name: git-gateway
  branch: main
  repo: 1226085293/blog

local_backend: true

media_folder: 'public/static'
public_folder: '/static'

collections:
- name: 'posts'
  label: 'Posts'
  folder: '/data/blog'
  create: true
  slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  fields:
    - name: 'layout'
      label: 'Layout'
      widget: 'hidden'
      default: 'posts'
    - name: 'title'
      label: 'Title'
      widget: 'string'
    - name: 'date'
      label: 'Date'
      widget: 'datetime'
      date_format: 'YYYY-MM-DD'
      time_format: false
    - name: 'thumbnail'
      label: 'Featured Image'
      widget: 'image'
    - name: 'body'
      label: 'Body'
      widget: 'markdown'
