name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 安装 sed
        run: |
          apt-get update && apt-get install -y sed

      # - name: 构建 github 文档
      #   env:
      #     NODE_OPTIONS: --max_old_space_size=8192
      #   run: |-
      #     pnpm run docs:build
      #     > docs/.nojekyll

      # - name: 部署 github 文档
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     # 这是文档部署到的分支名称
      #     branch: site
      #     folder: docs

      - name: 替换为 gitee 配置
        run: |
          sed -i 's/base: "\/"/base: "\/site\/"/' src.vuepress/config.ts

      - name: 构建 gitee 文档
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > docs/.nojekyll

      - name: 部署 gitee 文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: site-gitee
          folder: docs
